### ISSUE TITLE
Metrics to show - tracking which are visible in the app

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/actdev-ui#19]
Split-out from #13 because it's an important and self-standing topic and to avoid it getting buried. Propose we communicate and track what we aim to communicate will be in check-boxes to be updated in this first post of the issue after liaising with @joeytalbot in descending order of priority.

- [ ] Site-level metrics, to be available in [site.geojson](https://raw.githubusercontent.com/cyipt/actdev/main/data-small/great-kneighton/site.geojson) - currently most up-to-date version of the column names and contents can be found in [all-sites.geojson](https://github.com/cyipt/actdev/blob/main/data-small/all-sites.geojson) but this will also be made available in the site.geojson and all-sites.csv files:
  - [x] % active travel, baseline - could be a coloured going from red (e.g. less than 20% active) to green (e.g. more than 50% active as in LCID)
  - [x] % active travel Go Active same - see how we can improve the score!
  - [x] Mode share for % walk, cycle and drive, for baseline and scenario (this is shown in the stacked barchart in #13 )
  - [x] Trip frequency-distance by mode - in barplot and [mode-split.csv](https://github.com/cyipt/actdev/blob/main/data-small/great-kneighton/mode-split.csv)
  - [x] Median commute distance (km)
  - [ ] Distance to nearest town centre (km)
  - [ ] Average circuity for balanced cycle routes and walking routes (most important) (we also have columns reporting fast and quiet circuity) 
  - [ ] Average busyness for fast cycle routes
  - [x] ... See column names for other options, most important ones above
  
- [ ] Within site metrics - tbc but most likely also in all-sites.geojson, all-sites.csv and site.geojson, see https://github.com/cyipt/actdev/issues/93
  - [ ] Walking circuity
  - [ ] Cycling circuity
  - [ ] Driving circuity
  - [ ] Ratio of walking/cycling to driving circuity
  - [ ] Possible other options include level of overlap between walking/cycle and driving routes, as illustrated in prototype map infographic here: https://github.com/cyipt/actdev/issues/93#issuecomment-783402953 and busyness of on-site trips (stretch)

- [ ] Clockboard level data
  - [ ] Busyness of clockboard zones by route type
  - [ ] Circuity of regions by route type and mode
  - [ ] See additional variables in [dartboard.geojson](https://github.com/cyipt/actdev/blob/main/data-small/great-kneighton/dartboard.geojson) 
- [ ] Route network level data
  - [ ] Level of use in rnet fast/balanced/quiet/walking, see  https://github.com/cyipt/actdev/blob/main/data-small/great-kneighton/rnet-walk.geojson for example - we also have busyness for rnet-fast/balanced/quiet files
- [ ] Route level data - number of trips and average busyness, e.g. see https://github.com/cyipt/actdev/blob/main/data-small/great-kneighton/routes-fast.geojson

This will be the list of metrics described in other words @Siequnu and @mvl22 as follows:

> > I propose these be finished by the start of next week, so that I can have a definitive list of "ingredients". Could @Robinlovelace take lead on this? I.e. the stats, headline figures, external links.
> 
> To clarify, this is just saying we need to get the key metrics agreed. (All the other page components are known about now obviously.)

I will check-in with @joeytalbot and aim to get back to you by end of day on this, expect this issue to be edited!

**Comment by Robinlovelace** [comment]
Heads-up @Siequnu I think there's a decent list of raw 'ingredients'. We've tried to highlight the most important to show, but the design process will help boil these ingredients up to create a tasty visual broth!

**Comment by Siequnu** [comment]
> Heads-up @Siequnu I think there's a decent list of raw 'ingredients'. We've tried to highlight the most important to show, but the design process will help boil these ingredients up to create a tasty visual broth!

Deliciously put. 

Great to have a list to work off. Thanks for this.

**Comment by Siequnu** [comment]
I merged the final-ui branch with the master, so we can now iterate based on something tangible.

Currently I am headlining 4 figures: % cycle base, % walking base, % driving base, and site cycle circuity. The first three change when switching between modes and show a little indicator of the difference.

<img width="800" alt="Screenshot 2021-02-24 at 19 30 31" src="https://user-images.githubusercontent.com/11821606/108994443-c380a900-76d6-11eb-979b-e24f3ae9aee7.png">
<img width="655" alt="Screenshot 2021-02-24 at 19 30 38" src="https://user-images.githubusercontent.com/11821606/108994454-c8455d00-76d6-11eb-87b7-295fcf2a93a8.png">

I don't assume these are the final stats to be displayed — can we come up with a handful (currently 4) headline stats? It makes sense to have stats that differ between current and go active scenarios, for greater visual and cognitive impact.

**Comment by Siequnu** [comment]
The definition of the metrics is shown [here](https://github.com/cyipt/actdev-ui/blob/81f7c1c1a96145374a0661061b450938080322f8/js/actdev.js#L435-L459).

Each metric is stored as an object, currently as follows:

```
{
	name: 'percent_cycle_base',
	percentage: true,
	decimal_points: 0,
	go_active: 'percent_cycle_goactive'
}, 
```

**Comment by Siequnu** [comment]
The final UI is now live, so it' s a good time to revisit this and interrogate which stats are headlined.

**Comment by joeytalbot** [comment]
My suggestion for the 4 headline stats to highlight on the UI:
- percentage commute active (toggles between Current and Go Active scenarios)
- percentage commute drive (toggles between Current and Go Active scenarios)
- median commute distance
- in-site cycle circuity

A wider question: what about all the other metrics that don't form part of an infographic? Are we going to use them at all?

**Comment by mvl22** [comment]
> A wider question: what about all the other metrics that don't form part of an infographic? Are we going to use them at all?

I think we should show what is important, and not show what isn't. That said, the popups will show the full list anyway so if people want more obscure stuff they will find it there.

I think four headline figures is about the right number - any more will dilute their importance.

**Comment by mvl22** [comment]
This is the current state:

![Screenshot 2021-03-05 at 18 37 57](https://user-images.githubusercontent.com/361423/110158953-f23b0580-7de1-11eb-8083-0220e27c362b.png)

I'm concerned we've lost the circuity measurement.

@Robinlovelace, can you make a definitive decision on what the four metrics should be, or confirm that what's there is as you want it, so we can close this issue.

**Comment by Robinlovelace** [comment]
Let's keep it simple, % cycling, walking and driving are clear from the bar charts - note there are in-site and desire line level circuity - perhaps better called 'directness' - metrics for walking and cycling (by route type). I would tentatively say that 'active travel diversion factor', measured as a percentage calculated as:

(((cycling balanced diversion factor + walking diversion factor)/2)/driving diversion factor) * 100

Would be good. Could be shown in the app as:

Active travel diversion factor (less is better + i info tooltip): 98% outside site 80% in site.

Instead of the % driving stats (although I think they are important, can they pop out from and 'Extra info' button?) could be good. I'm open minded and tentative because want to hear what others think and see how it could look in the prototype before making any firm decisions, but think the key thing is to make the app more usable as per #33. Simple is good at this stage is my general thinking and we can always re-add metrics so no harm in removing them at this stage although I think the Median commute distance is key.

**Comment by Siequnu** [comment]
Note that it would be good if we can have stats that vary between the current and go active, for maximum impact.

**Comment by mvl22** [comment]
Can this be closed now? I'm not sure what if anything remains, @Robinlovelace.

**Comment by Siequnu** [comment]
I also agree that we’ve reached a balance point where a good amount of stats are shown through our infographic and more can be accessed through the map interface.

I think therefore this issue can be closed although should indeed be opened again if any additional stats need to be headlined.

**Comment by mvl22** [comment]
I think that a decision has been made clearly now that:

1) We will add back in the in-site circuity figure (which I definitely agree is important). That means five, not four figures.

2) The median commute distance would ideally be shown, but we then end up with 6 metrics which there isn't really space for; the mode split graph essentially shows this anyway, and it's in the higher text.

There is approval to move the 'View simulation button' into the map area if required, but this doesn't really solve the problem as there is still the Planning application button there anyway.

**Comment by Robinlovelace** [comment]
Please do include the median commute distance. Could just be "Distance 5km" at this prototype stage.

**Comment by Siequnu** [comment]
As the in-site circuity is a static figure, wouldn't it best go in the site description, along with median commute distance?

**Comment by Siequnu** [comment]
> Please do include the median commute distance. Could just be "Distance 5km" at this prototype stage.

I believe that's already being shown, in the site description.

**Comment by mvl22** [comment]
> As the in-site circuity is a static figure, wouldn't it best go in the site description, along with median commute distance?

I think it will have to. Otherwise we end up highlighting the odd situation where changing scenario to active travel still shows the same circuity, which a practitioner would immediately think is wrong.

**Comment by joeytalbot** [comment]
This looks good.

**Comment by mvl22** [comment]
There's now a link to /manual/#circuity, so please create that section of the manual with the anchor id `circuity` and it will link through correctly.
